### ISSUE TITLE
NFT cards for Ambal Winter 

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/hasten-contracts#12]
Make smart contract for NFT cards related to [https://github.com/fragcolor-xyz/ambal/issues/72](https://github.com/fragcolor-xyz/ambal/issues/72).

**Comment by alebaffa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/hasten-contracts/12?planning-poker) with Zenhub @sinkingsugar

**Comment by alebaffa** [comment]
Starting point: [https://github.com/alebaffa/poap-contracts/tree/master](https://github.com/alebaffa/poap-contracts/tree/master) .

**Comment by sinkingsugar** [comment]
Done here https://github.com/fragcolor-xyz/NFTGiftsFactory, we need the cards.

**Comment by sinkingsugar** [comment]
I need an estimate of 0 button :)

**Comment by alebaffa** [comment]
@sinkingsugar so, just need to deploy your factory and website will connect to it to mint?

**Comment by sinkingsugar** [comment]
We mint them, this is purely to gift already minted NFTs :)
