### ISSUE TITLE
Implement the "FragPass NFT" contract

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/hasten-contracts#13]

**Comment by aang114** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/hasten-contracts/13?planning-poker) with Zenhub @alebaffa @sinkingsugar

**Comment by alebaffa** [comment]
@aang114 what is FP NFT?

**Comment by alebaffa** [comment]
@aang114  This is done, right? Can we make a final estimate of 1 for this?

**Comment by aang114** [comment]
> @aang114 This is done, right? Can we make a final estimate of 1 for this and close it?

Okay

**Comment by sinkingsugar** [comment]
it's not done 100% yet
need token URI and other stuff fyi
Can make another issue about "finalizing" though.
