### ISSUE TITLE
Add Whitelist Functionality to the "RhythmRun NFT Contract" that is based on the holders of "FragPass NFTs" 

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/hasten-contracts#14]

**Comment by aang114** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/hasten-contracts/14?planning-poker) with Zenhub @alebaffa @sinkingsugar

**Comment by sinkingsugar** [comment]
What's this?
There is no RR NFT contract planned. it's a fragment

**Comment by aang114** [comment]
Sorry. I made this issue before we had the discussion
